Doc iteration userguide
milvus-io/milvus-docs pull request #1069
Opened 2021-11-05 10:23 UTC by LocoRichard

2021-11-09 09:10 UTC, claireyuw requested changes

2021-11-09 09:12 UTC, LocoRichard commented on site/en/home/home.md
> +Here you will learn about [what Milvus is](overview.md), and how to [install](install_standalone-docker.md), [use](manage_connection.md), and [deploy](aws.md) Milvus to build an [application](image_s
Angel said that the front end cannot render variables in this doc. Changing it to rc8

2021-11-09 09:17 UTC, LocoRichard commented on site/en/home/home.md
> +Here you will learn about [what Milvus is](overview.md), and how to [install](install_standalone-docker.md), [use](manage_connection.md), and [deploy](aws.md) Milvus to build an [application](image_s
Actually, I'll leave it to angela. This page is still about rc7, and I have no idea which must be be change. @YiyunNi

2021-11-09 09:21 UTC, LocoRichard commented on site/en/userGuide/manage_data.md
> +  Current release of Milvus only supports deleting entities by primary key.
those are a note followed by a caution.

2021-11-09 09:35 UTC, claireyuw commented on site/en/userGuide/manage_data.md
> +  Current release of Milvus only supports deleting entities by primary key.
Same rule. Note, caution, and warning are all notices.

2021-11-09 09:44 UTC, LocoRichard commented on site/en/userGuide/manage_index.md
> +This topic describes how to manage indexes in Milvus. See [Vector Index](index.md) and [Index Selection](index_selection.md) for more information.
Done. btw, you only need to specify a boolean expression during a query, which is essentially a filtering operation on the scalar field or pk field.

2021-11-10 08:28 UTC, claireyuw requested changes

2021-11-10 08:29 UTC, claireyuw commented
@LocoRichard Review is done except for `search.md`, `query.md`, and `hybridsearch.md`. These three need further discussion.

Please make changes to the rest of the files accordingly and apply those to CN files as well.

2021-11-12 03:39 UTC, merged