Update upgrade.md
milvus-io/milvus-docs pull request #1087
Opened 2021-11-09 07:20 UTC by YiyunNi

Updates include:
1. Replace the example in this tutorial.
2. Restructured the headings 
3. Stylistic changes to follow the Milvus doc style guide.

2021-11-09 07:36 UTC, YiyunNi commented
This PR will close issue #941 once merged,

2021-11-10 10:58 UTC, claireyuw requested changes

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +Run `$ kubectl get pods` to check the running pods. You can see the following output.
Do you need "If successful?"

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +Check the image tag for the pod `my-release-milvus-standalone-75c599fffc-6rwlj`. You can see your Milvus standalone version is v2.0.0-rc7.
Do you need "If successful?"

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +
Same comment as above. Up to you to decide.

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +Run the following commands to upgrade your Milvus version from v2.0.0-rc7 to v2.0.0-rc8.
As Claire said, please capitalize "RC."

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +$ helm upgrade my-release milvus/milvus --set cluster.enabled=true
Do we still need "--set cluster.enabled=true?"

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +
"RC." Please change globally.

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +When upgrading Milvus standalone version, old pods will be deleted. Therefore, the service may be offline for a short period of time.
I don't think you need "version" with "upgrading."
"When upgrading Milvus standalone" is good enough. 
Up to you anyway.

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +Run the following commands to check new Milvus versions. You can see there are several new versions after 2.0.0-rc7.
> new versions **later than** 2.0.0-**RC7**?

2021-11-10 11:13 UTC, chris-zilliz commented on site/en/adminGuide/upgrade.md
> +Run `$ helm list` again to check your Milvus version. You can see your Milvus cluster has been updated to v2.0.0-rc8.
updated or upgraded? Align, please.

2021-11-11 12:14 UTC, merged