Added Time Travel Reference
milvus-io/milvus-docs pull request #1147
Opened 2021-11-18 07:30 UTC by YiyunNi

2021-11-22 02:32 UTC, claireyuw requested changes
Please decide the scope of this reference doc as a *user doc* and work with the engineer to see if we should omit certain concepts in this topic or add more reference docs, e.g. a knowhere introduction doc.

2021-11-22 08:37 UTC, YiyunNi commented on site/en/reference/timetravel_ref.md
> +The search implementation for sealed segments and growing segments are slightly different. Because all CRUD operations within Milvus are executed in memory.  For sealed segments, you need to [load co
Yes

2021-11-22 09:27 UTC, czs007 commented on site/en/reference/timetravel_ref.md
> +During a search, if the search request received by the proxy contains the parameter, `travel_timestamp`, the value of this parameter will be passed to segcore, which filters the search results by tim
yes. @fishpenguin please introduce segcore briefly.

2021-11-23 06:12 UTC, fishpenguin commented on site/en/reference/timetravel_ref.md
> +During a search, if the search request received by the proxy contains the parameter, `travel_timestamp`, the value of this parameter will be passed to segcore, which filters the search results by tim
Segcore is the execution engine which supports concurrent insertion, deletion, query, index loading, monitoring and statistics of a segment data in memory.

2021-11-23 08:11 UTC, claireyuw requested changes

2021-11-23 08:11 UTC, claireyuw commented on site/en/reference/timetravel_ref.md
> +When searching in [segcore](https://github.com/milvus-io/milvus/tree/master/docs/design_docs/segcore), the execution engine which supports concurrent insertion, deletion, query, index loading, monito
And what happens after this bitmap containing all information is generated?

2021-11-23 08:21 UTC, merged