Add alias docs
milvus-io/milvus-docs pull request #1218
Opened 2021-12-10 08:42 UTC by LocoRichard

Fix #1197

2021-12-10 08:52 UTC, nameczz requested changes

2021-12-10 08:52 UTC, nameczz commented on site/en/userGuide/manage_collection.md
> +  collection_name: "example_collection",
remove collection_name: "example_collection",

2021-12-10 08:52 UTC, nameczz commented on site/zh-CN/userGuide/manage_collection.md
> +  collection_name: "example_collection",
same here

2021-12-15 03:44 UTC, LocoRichard commented
closing for other PR fixes this.

2021-12-15 03:44 UTC, closed without merging