Update hybridsearch.md
milvus-io/milvus-docs pull request #1427
Opened 2022-03-09 07:34 UTC by arthuo

Translate the English in the document into Chinese

2022-03-09 10:18 UTC, LocoRichard requested changes

2022-03-09 10:18 UTC, LocoRichard commented on site/zh-CN/userGuide/search/hybridsearch.md
> +下面的例子展示了如何在正则 [向量搜索](search.md) 的基础上进行混合搜索。假设你想基于书籍介绍的特征向量搜索某些书籍，然而你只需要特定 word count 范围内的书籍。你可以指定布尔表达式来过滤过滤搜索参数中的 `word_count` field。Milvus 只会在匹配表达式的 entity 中搜索相似的向量。
正则 --> 普通
Or simply delete it.

2022-03-09 10:18 UTC, LocoRichard commented on site/zh-CN/userGuide/search/hybridsearch.md
> +Milvus 中的所有搜索和查询操作都在内存中执行。在进行向量相似性搜索之前将 collection 加载到内存中。
查询-->结构化匹配

2022-03-09 10:18 UTC, LocoRichard commented on site/zh-CN/userGuide/search/hybridsearch.md
> +		<td>用于搜索的向量</td>
`。`

2022-03-09 10:18 UTC, LocoRichard commented on site/zh-CN/userGuide/search/hybridsearch.md
> +    <td>用于搜索的参数（作为对象）。</td>
~~作为~~

2022-03-09 10:19 UTC, LocoRichard commented
Hi @arthuo , Thank you! 
I have made a few feedbacks. The others are good enough to be merged.

2022-03-10 00:09 UTC, arthuo commented
> Hi @arthuo , Thank you! I have made a few feedbacks. The others are good enough to be merged.

Good morning.I have made changes based on the feedback. Thank you for your work.

2022-03-10 08:24 UTC, merged